[WIP] Secure authentication tokens
rundeck/rundeck pull request #6643
Opened 2020-11-26 21:11 UTC by ahormazabal

Implementation of hashing scheme to securely storage authentication tokens.

2020-12-14 22:31 UTC, ahormazabal commented
Documentation: https://github.com/rundeck/docs/pull/716

2020-12-16 20:25 UTC, sjrd218 approved these changes
Works for me.

2020-12-17 17:16 UTC, gschueler commented on rundeckapp/grails-app/assets/javascripts/user/profile.js
> +        console.log("Token display closing.")
```suggestion
```

2020-12-17 17:16 UTC, gschueler commented on rundeckapp/grails-app/assets/javascripts/user/profile.js
> +    console.log("adding new token to list")
```suggestion
```

2020-12-17 17:17 UTC, gschueler commented on rundeckapp/grails-app/assets/javascripts/user/profile.js
> +        console.log("Deleting token display")
```suggestion
```

2020-12-17 17:28 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
> +    private AuthToken generateAuthToken(
maybe pass in `AuthenticationToken` parameter instead of long parameter list

2020-12-17 20:02 UTC, gschueler requested changes

2020-12-17 20:02 UTC, gschueler commented on rundeckapp/grails-app/views/user/_token.gsp
> +        ${token.name}
if there is no name set, this cell will be empty.. perhaps "Unnamed"

2020-12-23 20:40 UTC, ahormazabal commented
Submitted requested improvements.

2020-12-24 17:47 UTC, gschueler commented on rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
> +//        }
just remove this
```suggestion
```

2020-12-24 17:52 UTC, gschueler approved these changes

2020-12-30 17:01 UTC, merged