Fix multiple SCM Integration Issues
rundeck/rundeck pull request #6839
Opened 2021-03-09 18:40 UTC by ltamaster

**Is this a bugfix, or an enhancement? Please describe.**
SCM Import/Export bug fixes and enhancements:

* Fix error 500 in the manual pull from remote repository.
* Storage was getting retrieved from cache, this was causing inconsistency issues when in cluster mode
* It validates that the SCM base directory configuration is not shared between any SCM configuration, either on the same project or with other projects
* Now it checks if the jobs being tracked were actually tracked for the configured repository, if not it will be removed from the validation to choose what message to show in the jobs page.

Enhancement: 
* User is now able to delete the SCM configuration once disabled
* Detects when local repo has a different version than jobs definition. Sync local repo version with the job definition.

Issues references: 

https://github.com/rundeckpro/rundeckpro/issues/1520
https://github.com/rundeckpro/rundeckpro/issues/1521
https://github.com/rundeckpro/rundeckpro/issues/1522
https://github.com/rundeckpro/rundeckpro/issues/1523
fixes #5179 
https://github.com/rundeckpro/rundeckpro/issues/1560
https://github.com/rundeckpro/rundeckpro/issues/1559
fixes #5815

2021-03-09 20:08 UTC, ltamaster commented
@Mergifyio rebase

2021-03-09 20:34 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
> +                                        loadedExportPlugins.remove(project)
why is it removing the loadedExportPlugin here?

2021-03-09 20:34 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
> +                for(String projectName : frameworkService.getRundeckFramework().getFrameworkProjectMgr().listFrameworkProjectNames()){
this is going to be very inefficient with a large number of projects.  can it just iterate on existing loadedPlugins?

2021-03-10 13:11 UTC, ltamaster commented
@Mergifyio rebase

2021-03-15 18:21 UTC, gschueler requested changes
I think `validateIntegrationDirectory` semantics should be moved into the git plugin.  it already does validation to check a unique project is used, it could also verify the import/export is unique for the basedir.

2021-03-15 18:24 UTC, gschueler requested changes
the method `loadPluginWithConfig` (and `loadExportPluginWithConfig` and `loadImportPluginWithConfig`) return a `CloseableProvider`.  This is provides a Closeable interface, and must be closed after it is used.  The normal flow for a plugin will initialize it at startup or first configuration and then close it when it is done.  There are now some other calls to `loadPluginWithConfig` which aren't correctly closing the result after they are done

2021-03-15 18:26 UTC, gschueler commented
I fixed one case where loadPluginWithConfig result was not being closed

2021-03-19 22:47 UTC, gschueler commented
testing using a local build and https://github.com/rundeckpro/scm-docker-demo

* fix #1523 confirmed for local dir
* for #1520 seems ok
* for #1521 weird behavior, and I could not verify job renaming works, because I cannot rename a job.
    * Actually i cannot edit a job at all via Rundeck GUI.  No changes in the job edit form are being applied
    * deleting a job works
    * creating a job works
    * no other changes take effect

2021-03-19 23:10 UTC, gschueler commented
* 1522: after cleaning up the test git repo to a clean state, i confirmed this is working as expected.  After pushing a new job to export repo, the job state is "?" and says "Export Status: Clean, not tracked for SCM Import"

2021-03-19 23:13 UTC, gschueler commented
confirmed for:

fixes #5179
rundeckpro/rundeckpro#1560
rundeckpro/rundeckpro#1559

2021-03-19 23:34 UTC, gschueler commented
#1585 seems fixed

2021-03-19 23:40 UTC, gschueler commented
investigating the issue with being unable to modify a job, but not sure if it is related to scm changes or not

2021-03-19 23:41 UTC, gschueler approved these changes

2021-03-19 23:47 UTC, gschueler commented
confirmed, the job rename issue is present in enterprise snapshot, I believe

2021-03-22 17:34 UTC, gschueler commented
confirmed #1521 appears fixed

2021-03-22 17:34 UTC, merged