WIP: adding access to key storage for webhooks
rundeck/rundeck pull request #6953
Opened 2021-04-06 18:20 UTC by chrismcg14

**Is this a bugfix, or an enhancement? Please describe.**
Add a the keyStorage service provider to the context services being passed to onevent, so web hook processing can use key storage

2021-04-09 21:14 UTC, ltamaster requested changes

2021-04-09 21:14 UTC, ltamaster commented on grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
> +            storageTreeWithContext(_) >> {Mock(KeyStorageTree)}
maybe you can move this to the `then` clause and mark the number of times this should be called (like 1* storageTreeWithContext(_) ...)

2021-04-14 15:45 UTC, ltamaster approved these changes
LGTM

2021-05-03 16:54 UTC, gschueler approved these changes

2021-05-03 16:54 UTC, merged