fix rundeckpro/rundeckpro#1621 fix rundeckpro/rundeckpro#1625
rundeck/rundeck pull request #7045
Opened 2021-05-10 16:06 UTC by imad6639

**Is this a bugfix, or an enhancement? Please describe.**
Enhancement - Allow export variables to be available for use in notifications for jobs and referenced jobs

**Describe the solution you've implemented**
When notifications are triggered, and map of exported variables are sent to the notification service

**Additional context**
Add any other context or screenshots about the change here.
fix rundeckpro/rundeckpro#1625
fix rundeckpro/rundeckpro#1626
fix rundeckpro/rundeckpro#1621
fix rundeckpro/rundeckpro#1616

2021-06-28 19:49 UTC, ProTip requested changes

2021-06-28 19:49 UTC, ProTip commented on rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
> +            props << export
`export` contains a `job` key at this point which ends up replacing the hand-crafted `props` key from line 788. I'm not sure what the impact of that is but:

* It adds a lot more keys to `job`. Was the intention of line 788 to limit the keys available?
* In the case of `group` the null coalesce to empty string gets defeated.

2021-06-29 05:12 UTC, ProTip approved these changes

2021-06-29 05:13 UTC, merged

2021-06-29 16:32 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
> -            }
i think this will break exported data vars for job references in the case where `jitem.ignoreNotifications` is true