Enh: Multi Input Style
rundeck/rundeck pull request #7364
Opened 2021-11-04 20:37 UTC by mishingo

**Is this a bugfix, or an enhancement? Please describe.**
Enhancement: improve appearance of multi input 

**Describe the solution you've implemented**
add style changes to update appearance

2021-11-04 20:37 UTC, mishingo commented
![image](https://user-images.githubusercontent.com/1903516/140416240-e41f8fd9-4738-4f21-b316-46a4c413f6eb.png)

2021-11-04 20:38 UTC, mishingo commented
![image](https://user-images.githubusercontent.com/1903516/140416334-8566cd9c-3cb9-42db-96db-72337609540a.png)

2021-11-09 19:26 UTC, qualman commented
Looks good but looks like it is failing Selenium tests?

2021-11-09 19:27 UTC, qualman requested changes
Address failing Selenium test

2021-11-09 22:53 UTC, gschueler commented
the borders around the Filter dropdown, and the Help button have a border-radius when it seems they shouldn't have one 
![Screen Shot 2021-11-09 at 2 52 26 PM](https://user-images.githubusercontent.com/55603/141018340-f4112c7b-22af-489d-b272-677055e005fe.png)
![Screen Shot 2021-11-09 at 2 52 32 PM](https://user-images.githubusercontent.com/55603/141018343-34430025-5997-4bf5-8a64-e19f42308fa6.png)

2021-11-10 17:23 UTC, gschueler requested changes

2021-11-10 17:23 UTC, gschueler commented on rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx
> +                <script id="filter_select_tokens" type="text/json">{"TOKEN":"6cb1a494ae5310e236adf5662ef5047bd330075b8f7d74b7be906893ab755189","URI":"/project/zingbats-west-prod-8/nodes"}</script>
```suggestion
```

2021-11-10 18:58 UTC, qualman commented
I cannot replicate the rounded corner issue and every other change looks good, so it's a go for me 👍🏻

2021-11-10 18:58 UTC, qualman approved these changes

2021-11-10 19:01 UTC, gschueler approved these changes

2021-11-10 21:48 UTC, merged