RUN-809: Moving packaging-core and pro to core repo
rundeck/rundeck pull request #7775
Opened 2022-06-17 14:22 UTC by carlosrfranco

2022-06-27 19:16 UTC, carlosrfranco commented
@Mergifyio rebase

2022-07-22 13:06 UTC, carlosrfranco commented
@Mergifyio rebase

2022-08-17 21:09 UTC, chrismcg14 commented
This is looking good. A couple of minor items:

1. the packaging submodule seems to have gotten committed
2. Restore proper version before merge

2022-08-17 21:26 UTC, chrismcg14 requested changes
v

2022-08-17 21:26 UTC, chrismcg14 commented on packaging/scripts/circle-build.sh
> +publish_pro() {
these pro methods can be removed since another build.sh file was added in pro

2022-08-23 23:13 UTC, gschueler commented
fyi: a change to packaging template will need to be incorporated here as well https://github.com/rundeck/packaging/pull/36

2022-09-02 16:58 UTC, gschueler commented on .circleci/config.yml
> +            branches: { only: /^RUN-809.*/ }
let's enable this for all branches, then we can merge

2022-09-02 16:59 UTC, gschueler commented on docker/debinstall/entry.sh
> +test -f "$HOME"/packaging/packaging/debdist/rundeck*.deb || {
nm, we can do this in a different pr

2022-09-07 22:41 UTC, gschueler approved these changes

2022-09-16 22:22 UTC, merged