fixed java string interpolation bug
rundeck/rundeck pull request #7791
Opened 2022-06-30 20:22 UTC by mcat115

I was using the debugger to trace an error I've been stuck on all day. Once I found it, I realized it was a bug. I found the message in the java file TypedStorageTreeImpl.java, but the string is hard coded with what looks to be interpolation, but since it's a java file I'm literally getting an error with the interpolation syntax instead of any data. So I fixed it to work with Java syntax instead of the broken Groovy syntax it was using. I also removed a period from the end of another plugin description to fit with the style I have been implementing in RUN-912

2022-07-20 17:00 UTC, ehe-pd commented on core/src/main/java/com/dtolabs/rundeck/core/storage/TypedStorageTreeImpl.java
> +        String errorMessage = "Path " + path + " does not store a password, content-type: " + contentType;
It's a good fix. 
The original error message is quite confusing; based on my understanding the problem is `Path <path> does not store a resource for content-type: <contentType>`.

2022-07-20 17:01 UTC, ehe-pd requested changes
Maybe we can make the error message more accurate and readable?

2022-07-20 19:53 UTC, eric-leihe approved these changes

2022-07-21 15:07 UTC, ehe-pd approved these changes

2022-07-21 16:31 UTC, merged

2022-08-08 16:59 UTC, fdevans commented
Is this customer visible?  If so, can we get a description or title that highlights what was fixed from their perspective?  If not, we can add the `release-notes/exclude` label to it.

2022-08-08 17:04 UTC, mcat115 commented
If the customer does not provide a password as needed for certain credentials, the error message will now say which password key path path is incorrectly configured instead of an incorrectly interpolated "path" variable. It is now functioning as was originally intended