RUN-1410: Add a new ExecutionLifecicleComponent
rundeck/rundeck pull request #8083
Opened 2023-01-12 21:54 UTC by ltamaster

**Is this a bugfix, or an enhancement? Please describe.**
Refactor ExecutionLifecyclePlugin to have a new ExecutionLifecycleComponent similar to JobLifecycleComponent. With this new Component, we can create an ExecutionLifecycle component that cannot be turned off by the final user.

**Describe the solution you've implemented**
add a new ExecutionLifecycleComponent interface. The current ExecutionLifecyclePlugin interface depends on the first one. 
Now both, the plugins and components are loaded in `ExecutionLifecycleComponentService`

**Describe alternatives you've considered**

**Additional context**

2023-01-17 23:05 UTC, gschueler requested changes

2023-01-18 12:50 UTC, ltamaster commented on rundeckapp/grails-app/services/rundeck/services/ExecutionLifecycleComponentService.groovy
> +class ExecutionLifecycleComponentService implements IExecutionLifecycleComponentService {
we need to do the same with `JobLifecycleComponentService`  I guess

2023-01-18 16:00 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ExecutionLifecycleComponentService.groovy
> +class ExecutionLifecycleComponentService implements IExecutionLifecycleComponentService {
@ltamaster yes we should

2023-01-18 18:38 UTC, gschueler commented on rundeckapp/src/main/groovy/rundeck/services/ExecutionLifecycleComponentService.groovy
> +    public static Logger log = LoggerFactory.getLogger(ExecutionLifecycleComponentService.class.name)
you can apply `@Slf4j` annotation to the class to set up the logger automatically

2023-01-18 18:40 UTC, gschueler approved these changes

2023-01-26 15:43 UTC, merged