RUN-199: Improve Authentication Options for Remote URL Option Input
rundeck/rundeck pull request #8193
Opened 2023-03-10 22:49 UTC by ltamaster

**Is this a bugfix, or an enhancement? Please describe.**
Enhancement: authentication method options as part of the Remote URL Option Input.

**Describe the solution you've implemented**

**Describe alternatives you've considered**

**Additional context**

2023-03-23 00:11 UTC, gschueler requested changes

2023-03-23 00:14 UTC, gschueler requested changes

2023-03-23 00:14 UTC, gschueler commented on rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
> +        1 * controller.logger.debug("API key authentication with Header apiKey")
Should avoid relying on side-effect of using the logger.debug in the test.

Perhaps introduce an interface that can be mocked.  E.g. `interface HttpClientCreator{ HttpClient<HttpResponse> createClient() }` then you can replace [this line](https://github.com/rundeck/rundeck/pull/8193/files#diff-0588b6c107c25b5c990676b0df69cfec52009719523a901e54dd5eb9feb91622R850) with a call to the HttpClientCreator. 

Then you can test the `setUri`, `setHeader` etc all have the right values

2023-03-23 20:43 UTC, gschueler commented on rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
> +                    }
I think you could just pass a closure, `{->new ApacheHttpClient()}` or even just `ApacheHttpClient.&newInstance` instead of an anonymous class

2023-03-23 22:16 UTC, gschueler commented on rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
> +        })
so Spock will evaluate this by expecting the closure inside the method call argument to work like a constraint and evaluates the [statements like assertions](https://spockframework.org/spock/docs/2.1/interaction_based_testing.html#_code_constraint) (in this case it still succeeds), but for side-effects like calling processor.accept here, you probably want to do it like this here and in the other tests: 

```suggestion
        1 * client.execute(_) >> {
            RequestProcessor processor = it[0]
            HttpResponse rsp = Mock(HttpResponse){
                getStatusLine()>>Mock(StatusLine){
                    getStatusCode()>>200
                }
                getEntity()>>Mock(HttpEntity){
                    getContent()>>new ByteArrayInputStream('{}'.getBytes());
                }
                getFirstHeader("Content-Type")>>Mock(Header){
                    getValue()>>"application/json"
                }
            }
            processor.accept(rsp)
        }
```

2023-03-27 15:36 UTC, gschueler approved these changes

2023-03-28 13:52 UTC, ltamaster commented
@sjrd218 I added small changes for the new `rundeck-data-shared` in order to avoid parse issues with `configMap` field.
I think the long-term solution is to include `JobOptionConfigData configData` as a field instead `configMap` but I have some dependency issues in  `rundeck-data-model`

2023-03-28 18:45 UTC, ltamaster commented on grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdOption.groovy
> +        configData.getJobOptionConfigEntries().stream().findFirst().orElse(null).toMap()
@sjrd218 sent a commit to fix that

2023-03-28 23:30 UTC, merged