RSE-326: Fix: Error responses including stacktraces
rundeck/rundeck pull request #8322
Opened 2023-05-12 14:02 UTC by L2JE

Ticket: https://pagerduty.atlassian.net/browse/RSE-326

#### Problem
When there's an internal error, the responses include information about the internal system (stacktraces).
![image](https://github.com/rundeck/rundeck/assets/49494423/67579e96-a10c-4170-9796-acfcdd93a9b8)
or
![image](https://github.com/rundeck/rundeck/assets/49494423/b3faaa9d-cf33-4959-a746-30b052567cf9)

#### Solution
Use an Interceptor that matches responses with internal server errors and render a default error page for any of them:
![image](https://github.com/rundeck/rundeck/assets/49494423/360e4201-dd26-4b1e-abf6-b448bb985d6f)

##### Previous behavior can be re-enabled for debug:
```
# In rundeck-config.properties to disable the interceptor
rundeck.feature.debug.showTracesOnResponse=false
```

2023-05-15 17:19 UTC, ronaveva commented
1. Is it possible to use the ConfigurationService? (instead of grailsApplication.config)
2. Is it possible to log the exception? sometimes this information is actually useful to find the root cause of an issue.

2023-05-16 14:33 UTC, L2JE commented
> 1. Is it possible to use the ConfigurationService? (instead of grailsApplication.config)
> 
> 2. Is it possible to log the exception? sometimes this information is actually useful to find the root cause of an issue.

1. I thought it could impact throughput but now I will run a stress test with and without using the ConfigurationService to see if it really does before making a change.

2. Even the unhandled exceptions are logged as usual before the `Interceptor.after` method is reached. The logging will depend on the rest of the infrastructure.

2023-05-17 14:19 UTC, L2JE commented
There's no notable difference between using a controller in the interceptor to access properties and not using it:

#### 10 concurrent users accessing `/user/login` 10000 times with the default behavior (`rundeck.feature.debug.showTracesOnResponse=false`)
![image](https://github.com/rundeck/rundeck/assets/49494423/761ddcca-9a06-47fe-ba9c-8c35b5b2f5fa)

**RC1**: where properties are accessed using `grailsApplication.config.getProperty('rundeck.feature.debug.showTracesOnResponse', 'false')`

**RC2**: where properties are accessed using `this.configurationService.getBoolean('feature', 'debug', 'showTracesOnResponse', false)`

2023-05-24 16:09 UTC, ronaveva approved these changes
LGTM, just make sure to add the new property to the doc.

2023-05-31 19:08 UTC, ronaveva requested changes
please check the 2 minor comments

2023-05-31 19:08 UTC, ronaveva commented on rundeckapp/src/test/groovy/rundeck/interceptors/InternalErrorsInterceptorSpec.groovy
> +        !interceptor.doesMatch()
shouldn't the response have some sort of exception?

2023-05-31 21:41 UTC, ronaveva approved these changes
LGTM

2023-06-20 13:56 UTC, merged