RSE-1003 Testdeck Migration: 7 test (See desc)
rundeck/rundeck pull request #8878
Opened 2024-02-02 16:13 UTC by DarwisNarvaezDev

1. test-project-import.sh
3. test-project-invalid.sh
5. test-project-json.sh
7. test-project-missing.sh
9. test-project-resources-404.sh
11. test-project-resources.sh
13. test-project-space-in-name-fails.sh

2024-02-06 16:05 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ImportSpec.groovy
> +                "config": [
why is this config needed if it is only checking the motd?

2024-02-06 16:13 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
> +        def apiVersion = 40
why is the api version being specify?

2024-02-06 16:17 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy
> +        client.apiVersion = 14 // as the original test
use the default api version unless the test is specifically for other API version

2024-02-06 16:20 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy
> +        validJsonParse != null
can another validation be added beside not null?

2024-02-06 16:26 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExportSpec.groovy
> +        exportResponse.headers('Content-Disposition')[0].contains("attachment")
can it validate that the file content is xxx size (or between x and y)?

2024-02-07 13:29 UTC, DarwisNarvaezDev commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
> +        def apiVersion = 40
removed test

2024-02-07 16:06 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecExportSpec.groovy
> +        def archivesCheckForAnotherExec = assertArchiveContents(Paths.get(pathToExecs3), [exec2.id] as List<String>)
shoulds this be part of the "then", instead of line 219?

2024-02-07 16:14 UTC, ronaveva commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy
> +    def "test-project-resources-404"(){
this test doesn't match the validations from the original test. The endpoint to request should be  "${APIURL}/project/${proj}/resources"

2024-02-07 16:49 UTC, ronaveva requested changes
Overall looks ok, just a couple of changes

- Use specific API version only if the test is intended to
- Don't use method names with file extension (.sh)

2024-02-08 15:49 UTC, ronaveva approved these changes
LGTM

2024-02-08 15:51 UTC, merged