added unit test for date time picker
rundeck/rundeck pull request #9100
Opened 2024-05-03 21:06 UTC by jayas006

**Is this a bugfix, or an enhancement? Please describe.**

**Describe the solution you've implemented**

**Describe alternatives you've considered**

**Additional context**

2024-05-31 03:07 UTC, smartinellibenedetti requested changes
Left some pointers, but recommend revisiting these tests, as a few of them seem to be redundant.

2024-05-31 03:07 UTC, smartinellibenedetti commented on rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
> +    await wrapper.setData({ time: newTime });
recommend replacing the wrapper.setData with an emit from timePicker (`update:modelValue`), ie:

timePicker.vm.$emit(`update:modelValue`, newTime)

2024-05-31 03:07 UTC, smartinellibenedetti commented on rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
> +    }
please remove the if, but keep the line 41.

2024-06-06 17:04 UTC, smartinellibenedetti approved these changes
Left 2 small tweaks but once you commit them, feel free to merge this PR.

2024-06-06 17:04 UTC, smartinellibenedetti commented on rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
> +    expect(datePicker.attributes("class")).toContain(wrapper.vm.dateClass);
suggest to change `wrapper.vm.dateClass` (both here and on the timepicker for the written class. It's more readable.

2024-06-06 17:04 UTC, smartinellibenedetti commented on rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
> +    expect(wrapper.find(".bs-date-picker").exists()).toBe(true);
Can remove those, they are redundant

2024-06-06 17:30 UTC, jayas006 commented
> Left 2 small tweaks but once you commit them, feel free to merge this PR.

Fixed

2024-06-11 14:34 UTC, smartinellibenedetti commented
there are some typescript errors that need to be adjusted in this unit tests

2024-06-11 16:38 UTC, merged