RUN-2267: new local node executor feature flag
rundeck/rundeck pull request #9144
Opened 2024-05-24 18:44 UTC by gschueler

**Is this a bugfix, or an enhancement? Please describe.**
Updates the “newlocal” node executor, to work as a drop in replacement for the old “local” node executor

- Execution context (env vars) and all log output should match the previous implementation
- It has the benefit of being able to kill child processes when the local process finishes
- It introduces an experimental flag to disable env var inheritance from the server process

**Describe the solution you've implemented**

Make some behind the scenes changes to enable a feature flag that can make the “newlocal” the default local executor

`rundeck.feature.newLocalNodeExecutor.enabled=true` will set it as the default local executor

Add a new functional test step in the CircleCI workflow was added “Test Feature NewLocalExec”

This runs the same “ExecutionOutputSpec” but with the newLocalNodeExecutor feature flag enabled, to validate the output is the same

.. if there are some other functional tests that use local node executor in specific ways, we can enable those tests with this feature flag as well

**Describe alternatives you've considered**

**Additional context**

2024-08-08 19:00 UTC, ahormazabal requested changes
Overall LGTM, only requesting minor changes.

Tested and works as expected, feature flag correctly switched the default executor.

Child Process killing tested OK, but won't work with processes that are run in background with &. 

As discussed, Runner is not supported yet but can be added in a next phase.

2024-08-08 19:00 UTC, ahormazabal commented on core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java
> +        handle.descendants().forEach(ScriptExecUtil::killProcessHandleDescend);
As discussed, just calling `ScriptExecUtil::killProcessHandle` should be enough here as `descendants()` already return children recursively.

2024-08-08 19:02 UTC, ahormazabal commented
> As discussed, Runner is not supported yet but can be added in a next phase.

Clarifying: Runned worked OK, but won't use the newlocal executor.

2024-08-08 22:18 UTC, gschueler commented on functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
> +      RUNDECK_FEATURE_XYZ_ENABLED: "true"
sure thing, sorry about that!

2024-08-12 15:11 UTC, ahormazabal approved these changes

2024-08-12 20:20 UTC, merged