init refactoring
rundeck/rundeck pull request #9435
Opened 2024-11-08 17:40 UTC by mrdubr

**Is this a bugfix, or an enhancement? Please describe.**

**Describe the solution you've implemented**

**Describe alternatives you've considered**

**Additional context**

2024-11-19 15:19 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
> -    def "test-job-flip-executionEnabled"(){
Moved to `JobScheduledSpec` where scheduled job specs live

2024-11-21 18:11 UTC, mrdubr commented on functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
> +      - "5005:5005"
enables remote debugging and jmx access

2024-11-21 18:40 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionStatusSpec.groovy
> +    def "job/id/run should get into timedout status"() {
SIde-effects of refactoring.
Moved here from `JobScheduledSpec.groovy`

2024-11-28 14:51 UTC, ahormazabal commented on functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginImportScheduledJobSpec.groovy
> +@ExcludePro
Why must this be excluded from pro?

2024-11-28 14:57 UTC, ahormazabal requested changes
LGTM but i need to get over two nits:
- Clarify why the test needs to be exluded from pro.
- Rebase the branch so it can pass the ci in rundeckpro.

2024-11-28 17:27 UTC, ahormazabal approved these changes

2024-11-28 18:24 UTC, merged