RUN-2619: Added Docker Commands and Rundeck Restart to BaseContainer Tests
rundeck/rundeck pull request #9492
Opened 2024-12-06 19:46 UTC by trodriguezpd

…st the jobqueue when the instance restarts

**Is this a bugfix, or an enhancement? Please describe.**
This is an enhancement, to allow docker restarts on functional tests, specifically for the job queue ones implemented in this ticket:

https://pagerduty.atlassian.net/browse/RUN-2619

**Describe the solution you've implemented**
I created a restar rundeck instance method in the test containers, and moved the dockerNodeAction to the BaseContainer class so they're shared between the different test suites. This allows to test behaviours like the job queue continues after an instance restart.  

**Describe alternatives you've considered**
Using the test containers provided methods to restart containers, but I couldn't find ones for the compose test suite

**Additional context**

2025-01-14 22:21 UTC, mrdubr requested changes
Please, see my comments.

I totally understand that the "container" modelling you have to deal with is rather confusing. However, let's try keep it as clean and improve what we can.

2025-01-14 22:21 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +            //Here we just ignore the exception since i couldn't find the root cause
In general, swallowing exceptions is a bad practice.
You should `log` them with the appropriate level.
Otherwise, how would we ever know why the `"Rundeck did not start"`

2025-01-14 22:24 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
As mentioned above, let's RdContainer to RdComposeContainer.
There will be some ripple effect, but I checked and it won't be that bad.

2025-01-22 18:36 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +    private static RdContainer RUNDECK_COMPOSE_CONTAINER
RdContainer was updated into RdComposeContainer

2025-01-22 18:50 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +                RUNDECK_COMPOSE_CONTAINER = rundeckContainer
Both vars were removed, I replaced them with just the plain container id, which is the only thing we need from the container currently.

Also to note, the ComposeContainer does not provide or have RdDockerContainer instances, we can only get a ContainerState info by searching by service name, but we have no way of returning a RdDockerContainer instance from the compose as they're not actually related as far as my understanding goes.

2025-01-22 18:54 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +        if(RUNDECK_COMPOSE_CONTAINER){
Thanks for the docs! It triggers me that it looks similar to js ternary 😂, I learned something new. Either way, since I now directly store the container id this method was removed

2025-01-22 18:56 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +    void dockerNodeAction(String action, String containerId) {
This was updated and now gets executed with the params of the instance instead of receiving them, also it was renamed

2025-01-22 18:56 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +    void waitForRundeckUp(RdClient client){
Same as on top, it was renamed and it does use the client of the current instance.

2025-01-22 18:57 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +        int count = 0
This was updated to reuse the wait with retry utils

2025-01-22 19:01 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +            println(process.getText())
This was a debugging leftover by accident, but I took the opportunity add both a stderr capture and the process exit code in the exception itself

2025-01-22 19:01 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +            throw new RuntimeException("Failed to ${action} container ${containerId}")
both the code and an stderr capture were added to the exception text

2025-01-22 19:03 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +
This was caused basically because I was told to move the dockerNodeAction from the Cluster setup into the BaseContainer and it mantained the naming, but now It has a proper naming and works with the instance instead of receiving container params

2025-01-22 19:05 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +            //Here we just ignore the exception since i couldn't find the root cause
This was updated with the wait and retry logic, I tried using the log var which gets defined by the @Slf4j annotation, but due to some lifecycle issues, considering we are restarting containers with a direct process instead of using TestContainers( which does not provide methods for this ) it caused a weird Exception. 

Now I log them by instantiating a logger directly in the catch clause. Also tried the List<Exception> accumulator and logging them after the waitfor, but the issue still popped up.

2025-01-22 19:05 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
renamed!

2025-01-23 18:36 UTC, mrdubr approved these changes
A few minor concerns. 
See my comments.
Once fixed, no need for another review.

2025-01-23 18:36 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
> +                "opt2-required": "true",
Do you need to document the ability to override these values in the function javadoc?

2025-01-23 18:36 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
> +                LoggerFactory.getLogger(BaseContainer.class).error(e.getMessage())
You do expect to see a few of these log lines in a "normal" flow, right?
In that case, the `error` level is a bit too harsh. 

```suggestion
                LoggerFactory.getLogger(BaseContainer.class).info(e.getMessage())
```

2025-01-28 13:27 UTC, trodriguezpd commented on functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
> +                "opt2-required": "true",
Both queue-enabled and queue-size are now documented

2025-01-28 17:18 UTC, mrdubr requested changes
Please, see my comments. Most are `nit`s. Some are not.

2025-01-28 17:18 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
> +         * Returns a boolean that verifies if the executions where executed sequentially,
nit:
In javadoc, you'd specify the return type in the `@return. Also, the best practices prescribe avoiding implementation details (e.g. start-date, end-date) and favour buinsiess meaning.
E.g.
```
Checks if executions were executed sequentially, meaning the execution at a position `n` has ended before the execution at position `n+1` has started.
```

2025-01-28 17:18 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
> +        static final haveExecutedSequentially(List<Execution> executions) {
The `org.rundeck.util.api.responses.execution.Execution` type does not provide `date-started` or `date-ended` properties. You're relying on the "hidden" jackson deserialization artifacts that are not guaranteed.

2025-01-28 17:21 UTC, mrdubr commented on functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
> +                    .every { pair -> pair[1]["date-started"]["unixtime"] >= pair[0]["date-ended"]["unixtime"] }
nit:
Only if you could say:
`pair[1].enderBeforeOrAt(pair[0])`
Leaving the knowledge of the start and end dates to the `Execution` class where it belongs ;-)

2025-02-11 15:38 UTC, mrdubr approved these changes
LGTM

2025-02-11 17:44 UTC, merged